### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by ericphanson** [ericphanson/SDPAFamily.jl#4]
- [x] BB for MacOS and Linux (https://github.com/ericphanson/SDPA_GMP.jl/pull/2)
- [x] Document windows experimental support
- [x] Tests of presolve
- [x] Float64 tests via MOI 
- [x] Tests via Convex.jl
- [x] Try with JuMP
- [x] example for the README
- [x] all tests called by runtests.jl passing so Travis gives meaningful info
- [x] failing tests diagnosed (to some extent) and filed as issues
- [x] https://github.com/ericphanson/SDPA_GMP.jl/issues/3
- [x] verbose flag in optimizer constructor
- [x] high precision tests (solve some problems with BigFloats to rtol=1e-30 or something like that). Otherwise, all our tests are the same as for Float64 solvers and don’t test the high precision bit.
- [x] Make presolve tests not fail on CI (robustify somehow...)
- [x] Add tests for QD and DD (can just run MOI + Convex tests with them too).
- [x] Decide if we want to rename this package and/or the builder repo, to account for QD and DD
- [x] Fix parsing bug with plain SDPA
- [x] https://github.com/ericphanson/SDPAFamily.jl/issues/12

**Comment by JiazhengZhu** [comment]
I have just updated the master branch with the changes.

**Comment by ericphanson** [comment]
I added high precision tests. But you’re checking off boxes faster than I’m adding them, so I think we’ll converge to a release soon ;). 

We should also run CI on Windows too, since we’re trying to support it. I think one is in my department; I’ll mess with the .travis.yml and try to get Windows tests working too, once the BB stuff is working.

**Comment by JiazhengZhu** [comment]
We could just apply a smaller tolerance for Convex.jl tests. `TOL=1e-4` works but we start to see fails when `TOL=1e-5` and we might have to change `param.sdpa` to accommodate for this.

**Comment by ericphanson** [comment]
We might need to update the Convex tests so that all the numeric types in the problems are BigFloats. Otherwise, they might be failing at small tolerances just because the problem was inaccurately specified, or we are comparing the results to imprecise outcomes.

**Comment by ericphanson** [comment]
Actually, a good way to do the Convex tests might be to change things on the Convex.jl side. Right now, I copied some of the Convex.jl tests over to the benchmarks folder to use for benchmarking. It's a bit annoying to have two copies of the same code though. But actually, I think there's a way to resolve that problem and the problem here, which is the following:

Convex.jl could hold a "problem repository", where all the test problems are organized (essentially like the Convex.jl benchmarks are now, which is based off of the MOI benchmark process). The way that works is there's a function for each test or related set of tests, which accepts a call-back to tell the function what exactly to do with the problem it constructs.

My thought is to add three more arguments to those functions: not just a call-back for solving the problem (or calling `Convex.conic_problem` to time that), but also a numeric type to construct the problem with, a boolean to say whether or not to test the outcomes, and a tolerance for the tests.

I think with that framework, Convex.jl's tests and benchmarks could be unified, and the tests could be easily used for SDPA-GMP. We wouldn't even need to add the code to this repo; we could do it the way the MOI tests are done, where you "ask MOI to test your solver" by saying calling things like `MOIT.testfunction(...`.

I think it would be a fair amount of work to copy all the test code into this style, but a lot of it could be automated with find and replace.

Maybe for the purpose of the SDPA-GMP release, we could not do that sort of testing yet, and just write 2-3 problems by hand and test that we can solve them to high precision. But then if we do set up such a framework with Convex, we can use that.

What do you think?

**Comment by JiazhengZhu** [comment]
This sounds like a good idea.

But further to robustifying the presolve tests: I tried calling `rationalize` to the matrix, and drop the almost zero entries caused by the imprecise conversion to rationals. But this doesn't always work either... We could just keep using the same set of random matrices by setting the random seed at the beginning of the test but this is of course far from ideal.

With respect to the failed tests: you just need presolve for those.

**Comment by ericphanson** [comment]
I wrote in the PR, but just to say, I already was setting a seed, but somehow that wasn't enough. I'm not sure why. I made the first couple sets of test more robust via rationals, but I'm not sure about the 2nd too-- actually, I don't remember if they were failing before or not. So maybe we can check off the robustify checkbox. I'll see if the tests pass on the PR (except for windows) and if it does I'll merge it and hand things back to you.

**Comment by JiazhengZhu** [comment]
I have updated SDPA_GMP so that -QD and -DD variants are using a more suitable set of parameters. I also included the quantum example as the first high-precision test. And now every line in presolve.jl is covered by our test examples.

However, to work with QD and DD precisions, we have to change their C++ source code as well. We don't have to do much, just need to replace the print format strings as we have done for -GMP. I don't have the write-access yet though: would you like me to do a PR instead?

**Comment by ericphanson** [comment]
Awesome! QD is quad-double while DD is double-double, so maybe we need different params for each? (a "double" is a `Float64`, but I don't think the precision is exactly additive...).

I added some `@info` logging to the high precision tests, and this is what I got (after running it once):
```
┌ Info: SDPA-dd solved the problem with an absolute error of 
│   error = 2.414116220042218105242451964241796884423701829416993449768311961552870951239157e-11
└   time = 0.040470209
┌ Info: SDPA-qd solved the problem with an absolute error of 
│   error = 2.414116220042218105242451964241796884423701829416993449768311961552870951239157e-11
└   time = 0.078630137
┌ Info: SDPA-gmp solved the problem with an absolute error of 
│   error = 2.300830505346617389783827706299894944830363297643029476460592026271340401539914e-31
└   time = 0.176531941
```
The time scaling is interesting; QD is about twice as long as DD, and GMP longer of course. It would be interesting to benchmark different size problems, etc. The precision is ~ 1e-11 for both DD and QD, but it sounds like that's why we need more digits out of the printing?

It would be interesting to do more benchmarking; one easy way will be to run Convex.jl's benchmarks with the three variants.

Re- precisions: That would be great! Yes, please PR my forks of those repos. 

One other thing that I'm sure you've noticed is that the first call is extremely slow; I got 129 seconds for the first call running those tests. I tried using https://github.com/timholy/SnoopCompile.jl to generate precompile statements to see if that helps. Using the SDPA-GMP tests with SnoopCompile generated ~30 precompile statements for SDPA_GMP.jl, and 3k statements for MOI. When I used just the SDPA-GMP statements, precompile time went up a bit, but first solve time did not go down (went to 132 seconds actually). When I added the 3k MOI statements, precompile time went up even higher... to 394 seconds. That's almost unusable I think. First solve time did not drop either-- well, 123 seconds. So the precompile file really didn't seem to help.

**Comment by JiazhengZhu** [comment]
Curiously my precompile time is not that bad: it is indeed slower for the first run but it's only ~3-5 secs on both my windows and linux laptops, so I haven't paid too much attention on this. Perhaps this is something specific to macos?

I'll make the PR later today :)

**Comment by ericphanson** [comment]
Oh interesting. Are you using Julia 1.1 or 1.2? And which MOI version?

Ok great!

**Comment by JiazhengZhu** [comment]
I'm using Julia 1.1:
```
    Status `~/.julia/environments/v1.1/Project.toml`
  [c52e3926] Atom v0.9.1
  [da1fd8a2] CodeTracking v0.5.8
  [f65535da] Convex v0.12.2 [`~/.julia/dev/Convex`]
  [14197337] GenericLinearAlgebra v0.1.1
  [7073ff75] IJulia v1.20.0
  [4076af6c] JuMP v0.20.0
  [e5e0dc1b] Juno v0.7.2
  [b8f27783] MathOptInterface v0.9.1
  [295af30f] Revise v2.1.9
  [c946c3f1] SCS v0.6.0
  [b9a10b5b] SDPA v0.2.0
  [bfe18334] SDPA_GMP v0.1.0 [`~/.julia/dev/SDPA_GMP`]
  [f0680fed] SemidefiniteOptInterface v0.5.1
```
Precompiling SDPA_GMP takes about 2~3 seconds and the first solve time is around 40 sec? I also disabled Revise.

I've made the two PRs to -dd and -qd code. But for some reason the precision is not too different from the two solvers. I made a change in the file_io to recalculate the primal obj value using the xVec solution and the coefficients. This seems to slightly improve the precision.

**Comment by ericphanson** [comment]
>I've made the two PRs to -dd and -qd code. But for some reason the precision is not too different from the two solvers.
Ok, thanks for the PRs. I haven't updated the binaries on BB; are you using ones you compiled yourself? Otherwise there should be no difference yet.

> I made a change in the file_io to recalculate the primal obj value using the xVec solution and the coefficients. This seems to slightly improve the precision.
I'm not convinced this is a good idea. My thought is we should report back `optimizer.primalobj` as whatever the optimizer tells us its objective value is, since the user can always recalculate the value themselves. If we do this, I think we are only losing information about what the optimizer is doing. That's OK when there are no bugs, but I worry doing things this way can hide bugs (what if the optimizer gives a primalobj that's waaay off, but we never see since we recalulcate things which means there is always consistency between the reported solution and the optimal value?).

**Comment by JiazhengZhu** [comment]
Okay I have undone the changes...

**Comment by JiazhengZhu** [comment]
I have this error when running the plain SDPA test though.
```
/home/jiazheng/.julia/dev/SDPA_GMP/deps/usr/bin/sdpa: error while loading shared libraries: libsdpa.so.0: cannot open shared object file: No such file or directory
Simple test with variant plain: Error During Test at /home/jiazheng/.julia/dev/SDPA_GMP/test/variant_test.jl:4
  Got exception outside of a @test
  failed process: Process(`/home/jiazheng/.julia/dev/SDPA_GMP/deps/usr/bin/sdpa -ds /tmp/tmp42wd4z/input.dat-s -o /tmp/tmp42wd4z/output.dat -p /home/jiazheng/.julia/dev/SDPA_GMP/deps/param_gmp.sdpa`, ProcessExited(127)) [127]
```
But running the binary directly in terminal then everything is fine?

**Comment by ericphanson** [comment]
Maybe delete `deps/usr`, run `] build`, and try again?

**Comment by ericphanson** [comment]
It looks like Travis has the same problem: https://travis-ci.com/ericphanson/SDPA_GMP.jl/jobs/231903695. I'll investigate

**Comment by ericphanson** [comment]
Ok, it should be fixed now; needed to add a library product. Now it can run the binary, and gets to the parsing error I mentioned in the PR.

**Comment by ericphanson** [comment]
I updated the binaries with the printing changes. Maybe the params need to be adjusted to make use of it?

**Comment by ericphanson** [comment]
For the WSL stuff: I won’t have access to a windows computer (besides Travis) for a week or two, so I’m not sure I’ll be able to help much. I suggest trying to get a binary working within WSL first (without Julia involved, just from bash), then trying to be able to call it from command prompt (via the WSL command but not in a bash shell), and then seeing if you can replicate that from Julia. Then to make it work on Travis and other people’s computers we’ll need to make sure the build.jl script is setting it up the same way as you have locally.

There should be no dynamic libraries going on, so you shouldn’t face the same problems as the plain SDPA case, but it’s definitely more complicated in other ways because it’s going via WSL.

I’m also ok with dropping windows / WSL from the release checklist. It would definitely be nice to have but since SDPA-GMP doesn’t compile directly on windows, it’s definitely harder to support.

**Comment by JiazhengZhu** [comment]
Over the weekend I have been trying to get -GMP -DD and -QD to compile. But for some reason the configure script for -DD and -QD would only recognise the library after running `sudo make install`, and installing to other directory without su privilege does not work.  

Although the cause is still unclear, it is possible to run as `root` user in wsl by calling `wsl -u root` so perhaps I can just write a bash script and ask Julia to do `run(``wsl -u root install.sh``)`. Thus although Julia runs with normal privilege and we won't have access to windows system files, we only need to edit linux files in this case. We can also have a softlink in PATH that points to the binary file and we don't have to run every call to SDPA as root. Does this sound like a feasible idea?

**Comment by ericphanson** [comment]
Why do we need compilers? We can't just use the binaries?

**Comment by JiazhengZhu** [comment]
Sorry I may have misunderstood you... But I thought since the binary is failing on Travis, perhaps it's safer to compile the binary on the target machine's wsl rather than compiling it using BinaryBuilder? I now have the binaries -dd and -qd running fine when called by julia. Would you like me just to repeat what has been done for the -gmp binary and just set them up as file dependencies?

**Comment by ericphanson** [comment]
Ah, sorry for not being clear. Yes, I think file dependencies are best (since no chance something goes wrong in the compile + you don’t need root), but only if they work! It seems the special WSL GMP binary doesn’t work on Travis, right? Does it work locally for you?

**Comment by JiazhengZhu** [comment]
Okay no problem. The master branch should now be updated with the full set of wsl binaries. I have tested them locally and they work fine but not sure if they will pass on travis.

**Comment by ericphanson** [comment]
Ok great. I think then we’re almost there! What do you think about SDPAFamily.jl instead of SDPA_GMP.jl?

**Comment by JiazhengZhu** [comment]
Sure that sounds like a more appropriate name. I think the recent MOI update just broke things a little bit: [this line](https://github.com/JuliaOpt/MathOptInterface.jl/blob/345c03b96b53a35f7e583754de81e584c3841bff/src/Bridges/Constraint/rsoc.jl#L28) has an explicit float64 so I might open an issue for this... I will set back the version on travis to see if it will pass.

**Comment by ericphanson** [comment]
Ah good find. You can use compat to choose 9.1 instead (in the Project.toml). Yes, please do open an issue.

On Travis, I’m seeing process failed on WSL which is too bad. Maybe we can mark windows as sort of experimentally supported, and also give some pointers to how to compile it yourself in the readme, and how to use a self-compiled version (with the environmental variables or just setting the binary path each time).

**Comment by JiazhengZhu** [comment]
Sadly the error in soc2psd bridge was not corrected until MOI v0.9.1 so the norm2 atoms for Convex fails. So for now we will have to wait for that issue being resolved.

**Comment by ericphanson** [comment]
Ah, so if I understand right, we need 9.1 to get rid of that bug, but then 9.1 introduces a Float64 conversion?

I think a conversion is definitely less bad than a bug— if we test at low precision do the tests still fail?

**Comment by JiazhengZhu** [comment]
Yes the tests are fine if we use Float64 but there are many Convex examples that use this bridge so we would change a significant portion of the tests to accommodate this...

**Comment by ericphanson** [comment]
Ah I see. What if we use BigFloats via Convex.jl but still only ask for atol =1e-3? Not saying that’s what we should do, but trying to understand where it goes wrong

**Comment by JiazhengZhu** [comment]
A problem of type bigfloat has all of its entries being bigfloat. So the hardcoded float64 in the bridge will not act on these constraints and will just give a method error, because MOI does not deal with operations with two different types of numbers.

**Comment by ericphanson** [comment]
Ahh I see! That makes sense. That’s why we’re getting method errors. Hmm ok, that is tough. 

Let me merge my “problem depot” to the MOI branch. Then we can use that for testing via Convex, and we can easily specify the problem type and swap it out. Well actually only Float64 is implemented, but we can use that for now. 

Maybe we should file an issue on this repo too, to acknowledge the issue with MOI. Then maybe we can start sending PRs to MOI. That seems like the most urgent problem, since we need MOI working to do anything.

**Comment by ericphanson** [comment]
I'll add an example to the readme in the next few days and get this registered :).
